root: ./

structure:
  readme: introduction.md
  summary: SUMMARY.md

redirects:
  # Core redirects
  getting-started/introduction: /introduction.md
  getting-started/authentication: /authentication.md
  
  # Device related redirects
  devices/android: /devices/configuration.md
  devices/ios: /devices/configuration.md
  reference/device-locale: /features/locale-settings.md
  reference/landscape-orientation-android-only: /features/orientation.md
  reference/orientation: /features/orientation.md
  reference/locale: /features/locale-settings.md
  
  # Feature redirects
  features/notifications: /features/test-execution.md
  features/google-play: /devices/configuration.md
  features/orientation: /features/orientation.md
  features/locale: /features/locale-settings.md
  features/artifacts: /features/download-artifacts.md
  features/reports: /features/report-formats.md
  features/execution: /features/test-execution.md
  
  # Core concepts redirects
  core/flow-management: /core/flow-selection.md
  core/env-vars: /core/environment-variables.md
  
  # Reference redirects
  reference/exit-codes: /reference/exit-codes.md
  reference/troubleshooting: /reference/troubleshooting.md
  
  # Main paths
  authentication: authentication.md
  features/test-execution: features/test-execution.md
  features/app-management: features/app-management.md
  features/orientation: features/orientation.md
  features/locale-settings: features/locale-settings.md
  features/async-execution: features/async-execution.md
  features/retry-strategies: features/retry-strategies.md
  features/report-formats: features/report-formats.md
  features/download-artifacts: features/download-artifacts.md
  features/quiet-mode: features/quiet-mode.md
  features/maestro-versions: features/maestro-versions.md
  devices/configuration: devices/configuration.md
  core/flow-selection: core/flow-selection.md
  core/environment-variables: core/environment-variables.md
  reference/exit-codes: reference/exit-codes.md
  reference/troubleshooting: reference/troubleshooting.md 